@define type integer;
@define type memoryword;
@define type char = 0..255;
@define type alphafile;
@define type boolean = 0..1;
@define type twohalves;
@define type ccharpointer;
@define type bytefile;
@define type fourquarters;
@define type wordfile;
@define function chr ();
@define const true;
@define const false;
@define @field int;
@define var mem;
@define @field hh;
@define @field rh;
@define @field lh;
@define @field b0;
@define @field b1;
@define @field b2;
@define @field b3;
@define procedure writeln ();
@define const stdout;
@define var eqtb;
@define procedure write ();
@define procedure incr ();
@define function odd ();
@define procedure decr ();
@define procedure flush ();
@define procedure uexit ();
@define function inputln ();
@define const stdin;
@define function abs ();
@define function toint ();
@define @field gr;
@define @field qqqq;
@define type real;
@define function fabs ();
@define function round ();
@define procedure aclose ();
@define function aopenout ();
@define function aopenin ();
@define function extensionirrelevantp ();
@define function maketextex;
@define function bopenin ();
@define function maketextfm;
@define function getc ();
@define function feof ();
@define procedure bclose ();
@define procedure writedvi ();
@define function bopenout ();
@define function wopenin ();
@define procedure undumpint ();
@define procedure undumpthings ();
@define procedure undumphh ();
@define procedure calledit ();
@define procedure setpaths ();
